version: '3.9'
services:
  frontend: 
    container_name: app_frontend
    build: ./frontend
    ports:
      - 5173:5173
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes:
      - ./frontend:/app-frontend
    depends_on:
      - backend
  backend:
    container_name: app_backend
    build: ./api
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    # command: dev
    volumes:
      - ./api:/app-backend
    environment:
      - PORT=3001
      - JWT_SECRET=secret